<?php

namespace Coolshop\CoolSonataTranslationBundle\Repository;

/**
 * CoolTranslationLocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoolTranslationLocaleRepository extends \Doctrine\ORM\EntityRepository
{
}
